version: '3'
services:
  discovery:
    image: microservice-docker-discovery:0.0.1-SNAPSHOT
    ports:
    - 8761:8761
  currency-converter:
    image: microservice-docker-currency-converter:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    ports:
      - 8100:8100
  currency-converter-audit:
    image: microservice-docker-currency-converter-audit:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
      - discovery
    ports:
      - 8101:8101